doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'

        # IMPORTANT: You MUST configure your server version,
        # either here or in the DATABASE_URL env var (see .env file)
        #server_version: '16'

        profiling_collect_backtrace: '%kernel.debug%'
        use_savepoints: true
    orm:
        auto_generate_proxy_classes: true
        enable_lazy_ghost_objects: true
        report_fields_where_declared: true
        validate_xml_mapping: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        identity_generation_preferences:
            Doctrine\DBAL\Platforms\PostgreSQLPlatform: identity
        auto_mapping: true
        mappings:
            App:
                type: attribute
                is_bundle: false
                dir: '%kernel.project_dir%/src/Entity/'
                prefix: 'App\Entity\'
                alias: App
            Assets:
                type: attribute
                is_bundle: false
                dir: '%kernel.project_dir%/src/Entity/Assets'
                prefix: 'App\Entity\Assets'
                alias: Assets
            Backgrounds:
                type: attribute
                is_bundle: false
                dir: '%kernel.project_dir%/src/Entity/Backgrounds'
                prefix: 'App\Entity\Backgrounds'
                alias: Backgrounds
            Classes:
                type: attribute
                is_bundle: false
                dir: '%kernel.project_dir%/src/Entity/Classes'
                prefix: 'App\Entity\Classes'
                alias: Classes
            Construct:
                type: attribute
                is_bundle: false
                dir: '%kernel.project_dir%/src/Entity/Construct'
                prefix: 'App\Entity\Construct'
                alias: Construct
            Items:
                type: attribute
                is_bundle: false
                dir: '%kernel.project_dir%/src/Entity/Items'
                prefix: 'App\Entity\Items'
                alias: Items
            Monsters:
                type: attribute
                is_bundle: false
                dir: '%kernel.project_dir%/src/Entity/Monsters'
                prefix: 'App\Entity\Monsters'
                alias: Monsters
            Races:
                type: attribute
                is_bundle: false
                dir: '%kernel.project_dir%/src/Entity/Races'
                prefix: 'App\Entity\Races'
                alias: Races
            Spells:
                type: attribute
                is_bundle: false
                dir: '%kernel.project_dir%/src/Entity/Spells'
                prefix: 'App\Entity\Spells'
                alias: Spells
        controller_resolver:
            auto_mapping: false

when@test:
    doctrine:
        dbal:
            # "TEST_TOKEN" is typically set by ParaTest
            dbname_suffix: '_test%env(default::TEST_TOKEN)%'

when@prod:
    doctrine:
        orm:
            auto_generate_proxy_classes: false
            proxy_dir: '%kernel.build_dir%/doctrine/orm/Proxies'
            query_cache_driver:
                type: pool
                pool: doctrine.system_cache_pool
            result_cache_driver:
                type: pool
                pool: doctrine.result_cache_pool

    framework:
        cache:
            pools:
                doctrine.result_cache_pool:
                    adapter: cache.app
                doctrine.system_cache_pool:
                    adapter: cache.system
