<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20250328072541 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE alignment (id INT AUTO_INCREMENT NOT NULL, name VARCHAR(255) NOT NULL, abbreviation VARCHAR(10) NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE bg (id INT AUTO_INCREMENT NOT NULL, source_id INT NOT NULL, source_part_id INT DEFAULT NULL, name VARCHAR(50) NOT NULL, slug VARCHAR(50) NOT NULL, d1 VARCHAR(1000) DEFAULT NULL, d2 VARCHAR(1000) DEFAULT NULL, d3 VARCHAR(1000) DEFAULT NULL, equipment VARCHAR(1000) NOT NULL, INDEX IDX_C5C4EF21953C1C61 (source_id), INDEX IDX_C5C4EF2153CF384 (source_part_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE bg_competence (bg_id INT NOT NULL, competence_id INT NOT NULL, INDEX IDX_A10985FB1A2100A8 (bg_id), INDEX IDX_A10985FB15761DAB (competence_id), PRIMARY KEY(bg_id, competence_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE bg_language (bg_id INT NOT NULL, language_id INT NOT NULL, INDEX IDX_4C16A1671A2100A8 (bg_id), INDEX IDX_4C16A16782F1BAF4 (language_id), PRIMARY KEY(bg_id, language_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE bgcarac (id INT AUTO_INCREMENT NOT NULL, bg_id INT NOT NULL, d1 VARCHAR(1000) DEFAULT NULL, d2 VARCHAR(1000) DEFAULT NULL, d3 VARCHAR(1000) DEFAULT NULL, UNIQUE INDEX UNIQ_3694F6911A2100A8 (bg_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE classe (id INT AUTO_INCREMENT NOT NULL, tool2_id INT DEFAULT NULL, spellcasting_id INT DEFAULT NULL, name VARCHAR(50) NOT NULL, slug VARCHAR(50) NOT NULL, d VARCHAR(1000) NOT NULL, dv INT NOT NULL, save JSON NOT NULL COMMENT \'(DC2Type:json)\', equipment1 VARCHAR(500) NOT NULL, equipment2 VARCHAR(500) DEFAULT NULL, equipment3 VARCHAR(500) DEFAULT NULL, equipment4 VARCHAR(500) DEFAULT NULL, INDEX IDX_8F87BF96568477C4 (tool2_id), UNIQUE INDEX UNIQ_8F87BF9633EF40B5 (spellcasting_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE `classe_armor` (classe_id INT NOT NULL, item_id INT NOT NULL, INDEX IDX_F650AAC48F5EA509 (classe_id), INDEX IDX_F650AAC4126F525E (item_id), PRIMARY KEY(classe_id, item_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE `classe_weapon` (classe_id INT NOT NULL, item_id INT NOT NULL, INDEX IDX_4178682C8F5EA509 (classe_id), INDEX IDX_4178682C126F525E (item_id), PRIMARY KEY(classe_id, item_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE `classe_tool` (classe_id INT NOT NULL, item_id INT NOT NULL, INDEX IDX_3EE04B378F5EA509 (classe_id), INDEX IDX_3EE04B37126F525E (item_id), PRIMARY KEY(classe_id, item_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE classe_competence (classe_id INT NOT NULL, competence_id INT NOT NULL, INDEX IDX_31EF89548F5EA509 (classe_id), INDEX IDX_31EF895415761DAB (competence_id), PRIMARY KEY(classe_id, competence_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE `classe_armors` (classe_id INT NOT NULL, item_subcategory_id INT NOT NULL, INDEX IDX_87F199088F5EA509 (classe_id), INDEX IDX_87F199084C2B59A3 (item_subcategory_id), PRIMARY KEY(classe_id, item_subcategory_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE `classe_weapons` (classe_id INT NOT NULL, item_subcategory_id INT NOT NULL, INDEX IDX_2997DB808F5EA509 (classe_id), INDEX IDX_2997DB804C2B59A3 (item_subcategory_id), PRIMARY KEY(classe_id, item_subcategory_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE classe_level (id INT AUTO_INCREMENT NOT NULL, classe_id INT NOT NULL, level INT NOT NULL, bm INT NOT NULL, cantrip_know INT DEFAULT NULL, spell_know INT DEFAULT NULL, s1 INT DEFAULT NULL, s2 INT DEFAULT NULL, s3 INT DEFAULT NULL, s4 INT DEFAULT NULL, s5 INT DEFAULT NULL, s6 INT DEFAULT NULL, s7 INT DEFAULT NULL, s8 INT DEFAULT NULL, s9 INT DEFAULT NULL, infusion_know INT DEFAULT NULL, infused_item INT DEFAULT NULL, rage INT DEFAULT NULL, rage_damage INT DEFAULT NULL, martial_art INT DEFAULT NULL, ki INT DEFAULT NULL, unarmored_move INT DEFAULT NULL, sneak_attack INT DEFAULT NULL, sorcery_point INT DEFAULT NULL, spell_slot INT DEFAULT NULL, slot_level INT DEFAULT NULL, invocation_know INT DEFAULT NULL, INDEX IDX_D39D982B8F5EA509 (classe_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE classe_spellcasting (id INT AUTO_INCREMENT NOT NULL, d VARCHAR(1000) NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE competence (id INT AUTO_INCREMENT NOT NULL, name VARCHAR(50) NOT NULL, category VARCHAR(20) NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE `condition` (id INT AUTO_INCREMENT NOT NULL, name VARCHAR(50) NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE creature_type (id INT AUTO_INCREMENT NOT NULL, name VARCHAR(255) NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE damage (id INT AUTO_INCREMENT NOT NULL, name VARCHAR(50) NOT NULL, abbreviation VARCHAR(255) NOT NULL, part VARCHAR(10) DEFAULT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE feat (id INT AUTO_INCREMENT NOT NULL, source_id INT NOT NULL, source_part_id INT DEFAULT NULL, name VARCHAR(255) NOT NULL, slug VARCHAR(255) NOT NULL, prerequisite VARCHAR(255) DEFAULT NULL, d1 VARCHAR(1000) NOT NULL, d2 VARCHAR(1000) DEFAULT NULL, d3 VARCHAR(1000) DEFAULT NULL, d4 VARCHAR(1000) DEFAULT NULL, d5 VARCHAR(1000) DEFAULT NULL, INDEX IDX_5A9B91CB953C1C61 (source_id), INDEX IDX_5A9B91CB53CF384 (source_part_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE item (id INT AUTO_INCREMENT NOT NULL, subcategory_id INT DEFAULT NULL, category_id INT NOT NULL, damage2_id INT DEFAULT NULL, source_id INT DEFAULT NULL, source_part_id INT DEFAULT NULL, name VARCHAR(50) NOT NULL, slug VARCHAR(50) NOT NULL, quantity INT DEFAULT NULL, rarity VARCHAR(50) DEFAULT NULL, type VARCHAR(50) DEFAULT NULL, cost INT DEFAULT NULL, weight INT DEFAULT NULL, ca INT DEFAULT NULL, ca_dex TINYINT(1) NOT NULL, ca_max TINYINT(1) NOT NULL, ca_str INT DEFAULT NULL, ca_stealth TINYINT(1) NOT NULL, ca_don VARCHAR(50) DEFAULT NULL, ca_doff VARCHAR(50) DEFAULT NULL, dice VARCHAR(10) DEFAULT NULL, link TINYINT(1) NOT NULL, damage VARCHAR(5) DEFAULT NULL, d1 VARCHAR(1000) DEFAULT NULL, d2 VARCHAR(1000) DEFAULT NULL, d3 VARCHAR(1000) DEFAULT NULL, d4 VARCHAR(1000) DEFAULT NULL, d5 VARCHAR(1000) DEFAULT NULL, INDEX IDX_1F1B251E5DC6FE57 (subcategory_id), INDEX IDX_1F1B251E12469DE2 (category_id), INDEX IDX_1F1B251E91B04077 (damage2_id), INDEX IDX_1F1B251E953C1C61 (source_id), INDEX IDX_1F1B251E53CF384 (source_part_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE item_category (id INT AUTO_INCREMENT NOT NULL, name VARCHAR(50) NOT NULL, slug VARCHAR(50) NOT NULL, d1 VARCHAR(1000) DEFAULT NULL, d2 VARCHAR(1000) DEFAULT NULL, d3 VARCHAR(1000) DEFAULT NULL, d4 VARCHAR(1000) DEFAULT NULL, d5 VARCHAR(1000) DEFAULT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE item_category_source (item_category_id INT NOT NULL, source_id INT NOT NULL, INDEX IDX_EAA36EAAF22EC5D4 (item_category_id), INDEX IDX_EAA36EAA953C1C61 (source_id), PRIMARY KEY(item_category_id, source_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE item_category_source_part (item_category_id INT NOT NULL, source_part_id INT NOT NULL, INDEX IDX_8AEBFF85F22EC5D4 (item_category_id), INDEX IDX_8AEBFF8553CF384 (source_part_id), PRIMARY KEY(item_category_id, source_part_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE item_property (id INT AUTO_INCREMENT NOT NULL, name VARCHAR(50) NOT NULL, slug VARCHAR(50) NOT NULL, part VARCHAR(50) DEFAULT NULL, d VARCHAR(1000) NOT NULL, show_skill TINYINT(1) NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE item_property_item (item_property_id INT NOT NULL, item_id INT NOT NULL, INDEX IDX_ECAF32FFB4FA4BDA (item_property_id), INDEX IDX_ECAF32FF126F525E (item_id), PRIMARY KEY(item_property_id, item_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE item_subcategory (id INT AUTO_INCREMENT NOT NULL, category_id INT NOT NULL, name VARCHAR(50) DEFAULT NULL, slug VARCHAR(50) NOT NULL, place INT NOT NULL, d1 VARCHAR(1000) DEFAULT NULL, d2 VARCHAR(1000) DEFAULT NULL, d3 VARCHAR(1000) DEFAULT NULL, d4 VARCHAR(1000) DEFAULT NULL, d5 VARCHAR(1000) DEFAULT NULL, INDEX IDX_EDB4FC7E12469DE2 (category_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE language (id INT AUTO_INCREMENT NOT NULL, name VARCHAR(1000) NOT NULL, abbreviation VARCHAR(20) NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE liste (id INT AUTO_INCREMENT NOT NULL, skill_id INT DEFAULT NULL, spell_id INT DEFAULT NULL, number INT NOT NULL, place INT NOT NULL, l1 VARCHAR(1000) NOT NULL, l2 VARCHAR(1000) NOT NULL, l3 VARCHAR(1000) DEFAULT NULL, l4 VARCHAR(1000) DEFAULT NULL, l5 VARCHAR(1000) DEFAULT NULL, l6 VARCHAR(1000) DEFAULT NULL, l7 VARCHAR(1000) DEFAULT NULL, l8 VARCHAR(1000) DEFAULT NULL, l9 VARCHAR(1000) DEFAULT NULL, l10 VARCHAR(1000) DEFAULT NULL, INDEX IDX_FCF22AF45585C142 (skill_id), INDEX IDX_FCF22AF4479EC90D (spell_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE liste_item_subcategory (liste_id INT NOT NULL, item_subcategory_id INT NOT NULL, INDEX IDX_A97D3CC3E85441D8 (liste_id), INDEX IDX_A97D3CC34C2B59A3 (item_subcategory_id), PRIMARY KEY(liste_id, item_subcategory_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE race (id INT AUTO_INCREMENT NOT NULL, slug VARCHAR(50) NOT NULL, name VARCHAR(50) NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE race_source (id INT AUTO_INCREMENT NOT NULL, race_id INT NOT NULL, source_id INT NOT NULL, source_part_id INT DEFAULT NULL, d1 VARCHAR(1000) NOT NULL, d2 VARCHAR(1000) DEFAULT NULL, d3 VARCHAR(1000) DEFAULT NULL, ability VARCHAR(255) DEFAULT NULL, age VARCHAR(1000) DEFAULT NULL, alignment VARCHAR(1000) DEFAULT NULL, size VARCHAR(1000) DEFAULT NULL, speed VARCHAR(1000) DEFAULT NULL, INDEX IDX_35DC61A06E59D40D (race_id), INDEX IDX_35DC61A0953C1C61 (source_id), INDEX IDX_35DC61A053CF384 (source_part_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE race_source_language (race_source_id INT NOT NULL, language_id INT NOT NULL, INDEX IDX_3A2AE9334CBA5C7C (race_source_id), INDEX IDX_3A2AE93382F1BAF4 (language_id), PRIMARY KEY(race_source_id, language_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE race_subrace (id INT AUTO_INCREMENT NOT NULL, source_id INT NOT NULL, slug VARCHAR(20) NOT NULL, name VARCHAR(50) NOT NULL, d1 VARCHAR(1000) DEFAULT NULL, d2 VARCHAR(1000) DEFAULT NULL, d3 VARCHAR(1000) DEFAULT NULL, ability VARCHAR(1000) DEFAULT NULL, INDEX IDX_1C6A1C54953C1C61 (source_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE sb (id INT AUTO_INCREMENT NOT NULL, type_id INT NOT NULL, source_id INT DEFAULT NULL, source_part_id INT DEFAULT NULL, alignment_id INT DEFAULT NULL, name_fr VARCHAR(50) NOT NULL, name_eng VARCHAR(50) NOT NULL, slug VARCHAR(20) NOT NULL, category VARCHAR(20) NOT NULL, type2 VARCHAR(50) DEFAULT NULL, sizes JSON NOT NULL COMMENT \'(DC2Type:json)\', size_inf TINYINT(1) NOT NULL, size_sup TINYINT(1) NOT NULL, ca INT DEFAULT NULL, armor VARCHAR(50) DEFAULT NULL, pv INT DEFAULT NULL, dv VARCHAR(50) DEFAULT NULL, strenght INT NOT NULL, dexterity INT NOT NULL, constitution INT NOT NULL, intelligence INT NOT NULL, wisdow INT NOT NULL, charisma INT NOT NULL, save VARCHAR(50) DEFAULT NULL, competence VARCHAR(50) DEFAULT NULL, pp INT DEFAULT NULL, pp2 VARCHAR(50) DEFAULT NULL, fp DOUBLE PRECISION DEFAULT NULL, xp INT DEFAULT NULL, bm VARCHAR(50) DEFAULT NULL, d VARCHAR(800) NOT NULL, cac_t VARCHAR(50) DEFAULT NULL, cac_r VARCHAR(50) DEFAULT NULL, cac_d VARCHAR(50) DEFAULT NULL, range_t VARCHAR(50) DEFAULT NULL, range_r VARCHAR(50) DEFAULT NULL, range_d VARCHAR(50) DEFAULT NULL, INDEX IDX_E67738BEC54C8C93 (type_id), INDEX IDX_E67738BE953C1C61 (source_id), INDEX IDX_E67738BE53CF384 (source_part_id), INDEX IDX_E67738BEAB7AC2A0 (alignment_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE sb_sense (sb_id INT NOT NULL, sense_id INT NOT NULL, INDEX IDX_6F056A12707F4EA8 (sb_id), INDEX IDX_6F056A128707C57E (sense_id), PRIMARY KEY(sb_id, sense_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE sb_speed (sb_id INT NOT NULL, speed_id INT NOT NULL, INDEX IDX_6F08A71F707F4EA8 (sb_id), INDEX IDX_6F08A71F8F3A8393 (speed_id), PRIMARY KEY(sb_id, speed_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE sbskill (id INT AUTO_INCREMENT NOT NULL, damage_id INT DEFAULT NULL, type VARCHAR(10) NOT NULL, name VARCHAR(20) NOT NULL, part VARCHAR(20) DEFAULT NULL, d VARCHAR(1000) DEFAULT NULL, type_attack VARCHAR(20) DEFAULT NULL, target VARCHAR(50) DEFAULT NULL, INDEX IDX_9DCFA8F36CE425B7 (damage_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE sbskill_sb (sbskill_id INT NOT NULL, sb_id INT NOT NULL, INDEX IDX_E588BE0ABCC6E1E4 (sbskill_id), INDEX IDX_E588BE0A707F4EA8 (sb_id), PRIMARY KEY(sbskill_id, sb_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE sbspecialty (id INT AUTO_INCREMENT NOT NULL, monster_id INT NOT NULL, skill_id INT NOT NULL, d VARCHAR(1000) NOT NULL, INDEX IDX_DF3AE311C5FF1223 (monster_id), INDEX IDX_DF3AE3115585C142 (skill_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE school (id INT AUTO_INCREMENT NOT NULL, name VARCHAR(20) NOT NULL, slug VARCHAR(20) NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE sense (id INT AUTO_INCREMENT NOT NULL, name VARCHAR(255) NOT NULL, abbreviation VARCHAR(50) NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE skill (id INT AUTO_INCREMENT NOT NULL, feat_id INT DEFAULT NULL, spellcasting_id INT DEFAULT NULL, monster_id INT DEFAULT NULL, name VARCHAR(100) DEFAULT NULL, level INT DEFAULT NULL, show_skill TINYINT(1) NOT NULL, optional TINYINT(1) NOT NULL, d1 VARCHAR(1000) DEFAULT NULL, d2 VARCHAR(1000) DEFAULT NULL, d3 VARCHAR(1000) DEFAULT NULL, d4 VARCHAR(1000) DEFAULT NULL, d5 VARCHAR(1000) DEFAULT NULL, d6 VARCHAR(1000) DEFAULT NULL, d7 VARCHAR(1000) DEFAULT NULL, d8 VARCHAR(1000) DEFAULT NULL, d9 VARCHAR(1000) DEFAULT NULL, d10 VARCHAR(1000) DEFAULT NULL, type VARCHAR(10) DEFAULT NULL, part VARCHAR(20) DEFAULT NULL, attack_type VARCHAR(3) DEFAULT NULL, damage VARCHAR(100) DEFAULT NULL, target VARCHAR(100) DEFAULT NULL, INDEX IDX_5E3DE477F43C4D5C (feat_id), INDEX IDX_5E3DE47733EF40B5 (spellcasting_id), UNIQUE INDEX UNIQ_5E3DE477C5FF1223 (monster_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE skill_bg (skill_id INT NOT NULL, bg_id INT NOT NULL, INDEX IDX_2F7849335585C142 (skill_id), INDEX IDX_2F7849331A2100A8 (bg_id), PRIMARY KEY(skill_id, bg_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE skill_item_category (skill_id INT NOT NULL, item_category_id INT NOT NULL, INDEX IDX_84DDDCB65585C142 (skill_id), INDEX IDX_84DDDCB6F22EC5D4 (item_category_id), PRIMARY KEY(skill_id, item_category_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE skill_item_subcategory (skill_id INT NOT NULL, item_subcategory_id INT NOT NULL, INDEX IDX_6DE75AC65585C142 (skill_id), INDEX IDX_6DE75AC64C2B59A3 (item_subcategory_id), PRIMARY KEY(skill_id, item_subcategory_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE skill_classe_level (skill_id INT NOT NULL, classe_level_id INT NOT NULL, INDEX IDX_41F108295585C142 (skill_id), INDEX IDX_41F10829657F8309 (classe_level_id), PRIMARY KEY(skill_id, classe_level_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE skill_specialty_item (skill_id INT NOT NULL, specialty_item_id INT NOT NULL, INDEX IDX_17071ED65585C142 (skill_id), INDEX IDX_17071ED6605A4EC1 (specialty_item_id), PRIMARY KEY(skill_id, specialty_item_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE skill_race_source (skill_id INT NOT NULL, race_source_id INT NOT NULL, INDEX IDX_8BC2F86C5585C142 (skill_id), INDEX IDX_8BC2F86C4CBA5C7C (race_source_id), PRIMARY KEY(skill_id, race_source_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE skill_race_subrace (skill_id INT NOT NULL, race_subrace_id INT NOT NULL, INDEX IDX_8E068C565585C142 (skill_id), INDEX IDX_8E068C5646E4965B (race_subrace_id), PRIMARY KEY(skill_id, race_subrace_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE source (id INT AUTO_INCREMENT NOT NULL, name VARCHAR(255) NOT NULL, abbreviation VARCHAR(10) NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE source_part (id INT AUTO_INCREMENT NOT NULL, source_id INT NOT NULL, number INT NOT NULL, name VARCHAR(255) NOT NULL, INDEX IDX_4885F5C5953C1C61 (source_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE specialty (id INT AUTO_INCREMENT NOT NULL, classe_id INT NOT NULL, name VARCHAR(50) NOT NULL, slug VARCHAR(50) NOT NULL, d VARCHAR(1000) DEFAULT NULL, UNIQUE INDEX UNIQ_E066A6EC8F5EA509 (classe_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE specialty_item (id INT AUTO_INCREMENT NOT NULL, part1 VARCHAR(20) DEFAULT NULL, part2 VARCHAR(10) DEFAULT NULL, name VARCHAR(50) NOT NULL, slug VARCHAR(50) NOT NULL, d1 VARCHAR(1000) DEFAULT NULL, d2 VARCHAR(1000) DEFAULT NULL, d3 VARCHAR(1000) DEFAULT NULL, d4 VARCHAR(1000) DEFAULT NULL, d5 VARCHAR(1000) DEFAULT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE specialty_item_specialty (specialty_item_id INT NOT NULL, specialty_id INT NOT NULL, INDEX IDX_29DF2BC8605A4EC1 (specialty_item_id), INDEX IDX_29DF2BC89A353316 (specialty_id), PRIMARY KEY(specialty_item_id, specialty_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE specialty_item_source (specialty_item_id INT NOT NULL, source_id INT NOT NULL, INDEX IDX_355673FC605A4EC1 (specialty_item_id), INDEX IDX_355673FC953C1C61 (source_id), PRIMARY KEY(specialty_item_id, source_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE specialty_item_source_part (specialty_item_id INT NOT NULL, source_part_id INT NOT NULL, INDEX IDX_2A642247605A4EC1 (specialty_item_id), INDEX IDX_2A64224753CF384 (source_part_id), PRIMARY KEY(specialty_item_id, source_part_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE speed (id INT AUTO_INCREMENT NOT NULL, name VARCHAR(255) NOT NULL, abbreviation VARCHAR(255) NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE spell (id INT AUTO_INCREMENT NOT NULL, school_id INT NOT NULL, source_id INT DEFAULT NULL, source_part_id INT DEFAULT NULL, slug VARCHAR(20) NOT NULL, name_fr VARCHAR(20) NOT NULL, name_eng VARCHAR(20) NOT NULL, level INT NOT NULL, ritual TINYINT(1) NOT NULL, casting VARCHAR(20) NOT NULL, range1 VARCHAR(20) NOT NULL, range2 VARCHAR(50) DEFAULT NULL, components JSON NOT NULL COMMENT \'(DC2Type:json)\', materials VARCHAR(100) DEFAULT NULL, duration VARCHAR(50) NOT NULL, concentration TINYINT(1) NOT NULL, short VARCHAR(500) NOT NULL, d1 VARCHAR(1000) NOT NULL, d2 VARCHAR(1000) DEFAULT NULL, d3 VARCHAR(1000) DEFAULT NULL, d4 VARCHAR(1000) DEFAULT NULL, d5 VARCHAR(1000) DEFAULT NULL, d6 VARCHAR(1000) DEFAULT NULL, d7 VARCHAR(1000) DEFAULT NULL, d8 VARCHAR(1000) DEFAULT NULL, d9 VARCHAR(1000) DEFAULT NULL, d10 VARCHAR(1000) DEFAULT NULL, higher VARCHAR(1000) DEFAULT NULL, INDEX IDX_D03FCD8DC32A47EE (school_id), INDEX IDX_D03FCD8D953C1C61 (source_id), INDEX IDX_D03FCD8D53CF384 (source_part_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE spell_classe (spell_id INT NOT NULL, classe_id INT NOT NULL, INDEX IDX_37264883479EC90D (spell_id), INDEX IDX_372648838F5EA509 (classe_id), PRIMARY KEY(spell_id, classe_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE `classe_spell_expanded` (spell_id INT NOT NULL, classe_id INT NOT NULL, INDEX IDX_1ADD7654479EC90D (spell_id), INDEX IDX_1ADD76548F5EA509 (classe_id), PRIMARY KEY(spell_id, classe_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE subskill (id INT AUTO_INCREMENT NOT NULL, skill_id INT DEFAULT NULL, t1 VARCHAR(100) DEFAULT NULL, d1 VARCHAR(1000) DEFAULT NULL, d2 VARCHAR(1000) DEFAULT NULL, d3 VARCHAR(1000) DEFAULT NULL, INDEX IDX_248E0BAD5585C142 (skill_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE `table` (id INT AUTO_INCREMENT NOT NULL, skill_id INT DEFAULT NULL, bg_carac_id INT DEFAULT NULL, spell_id INT DEFAULT NULL, number INT NOT NULL, place INT NOT NULL, name VARCHAR(255) DEFAULT NULL, INDEX IDX_F6298F465585C142 (skill_id), INDEX IDX_F6298F46DC61594A (bg_carac_id), INDEX IDX_F6298F46479EC90D (spell_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE table_item (table_id INT NOT NULL, item_id INT NOT NULL, INDEX IDX_55CD65D5ECFF285C (table_id), INDEX IDX_55CD65D5126F525E (item_id), PRIMARY KEY(table_id, item_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE table_item_subcategory (table_id INT NOT NULL, item_subcategory_id INT NOT NULL, INDEX IDX_379EF18ECFF285C (table_id), INDEX IDX_379EF184C2B59A3 (item_subcategory_id), PRIMARY KEY(table_id, item_subcategory_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE table_specialty_item (table_id INT NOT NULL, specialty_item_id INT NOT NULL, INDEX IDX_ABFADE81ECFF285C (table_id), INDEX IDX_ABFADE81605A4EC1 (specialty_item_id), PRIMARY KEY(table_id, specialty_item_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE table_race_source (table_id INT NOT NULL, race_source_id INT NOT NULL, INDEX IDX_682921DECFF285C (table_id), INDEX IDX_682921D4CBA5C7C (race_source_id), PRIMARY KEY(table_id, race_source_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE table_race_subrace (table_id INT NOT NULL, race_subrace_id INT NOT NULL, INDEX IDX_A9898D96ECFF285C (table_id), INDEX IDX_A9898D9646E4965B (race_subrace_id), PRIMARY KEY(table_id, race_subrace_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE table_row (id INT AUTO_INCREMENT NOT NULL, tableau_id INT NOT NULL, number INT NOT NULL, d1 VARCHAR(255) NOT NULL, d2 VARCHAR(1000) NOT NULL, d3 VARCHAR(1000) DEFAULT NULL, d4 VARCHAR(1000) DEFAULT NULL, d5 VARCHAR(1000) DEFAULT NULL, d6 VARCHAR(1000) DEFAULT NULL, d7 VARCHAR(1000) DEFAULT NULL, d8 VARCHAR(1000) NOT NULL, INDEX IDX_8DD57CBFB062D5BC (tableau_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE user (id INT AUTO_INCREMENT NOT NULL, email VARCHAR(180) NOT NULL, roles JSON NOT NULL COMMENT \'(DC2Type:json)\', password VARCHAR(255) NOT NULL, name VARCHAR(255) NOT NULL, UNIQUE INDEX UNIQ_IDENTIFIER_EMAIL (email), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE messenger_messages (id BIGINT AUTO_INCREMENT NOT NULL, body LONGTEXT NOT NULL, headers LONGTEXT NOT NULL, queue_name VARCHAR(190) NOT NULL, created_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', available_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', delivered_at DATETIME DEFAULT NULL COMMENT \'(DC2Type:datetime_immutable)\', INDEX IDX_75EA56E0FB7336F0 (queue_name), INDEX IDX_75EA56E0E3BD61CE (available_at), INDEX IDX_75EA56E016BA31DB (delivered_at), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('ALTER TABLE bg ADD CONSTRAINT FK_C5C4EF21953C1C61 FOREIGN KEY (source_id) REFERENCES source (id)');
        $this->addSql('ALTER TABLE bg ADD CONSTRAINT FK_C5C4EF2153CF384 FOREIGN KEY (source_part_id) REFERENCES source_part (id)');
        $this->addSql('ALTER TABLE bg_competence ADD CONSTRAINT FK_A10985FB1A2100A8 FOREIGN KEY (bg_id) REFERENCES bg (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE bg_competence ADD CONSTRAINT FK_A10985FB15761DAB FOREIGN KEY (competence_id) REFERENCES competence (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE bg_language ADD CONSTRAINT FK_4C16A1671A2100A8 FOREIGN KEY (bg_id) REFERENCES bg (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE bg_language ADD CONSTRAINT FK_4C16A16782F1BAF4 FOREIGN KEY (language_id) REFERENCES language (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE bgcarac ADD CONSTRAINT FK_3694F6911A2100A8 FOREIGN KEY (bg_id) REFERENCES bg (id)');
        $this->addSql('ALTER TABLE classe ADD CONSTRAINT FK_8F87BF96568477C4 FOREIGN KEY (tool2_id) REFERENCES item_category (id)');
        $this->addSql('ALTER TABLE classe ADD CONSTRAINT FK_8F87BF9633EF40B5 FOREIGN KEY (spellcasting_id) REFERENCES classe_spellcasting (id)');
        $this->addSql('ALTER TABLE `classe_armor` ADD CONSTRAINT FK_F650AAC48F5EA509 FOREIGN KEY (classe_id) REFERENCES classe (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE `classe_armor` ADD CONSTRAINT FK_F650AAC4126F525E FOREIGN KEY (item_id) REFERENCES item (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE `classe_weapon` ADD CONSTRAINT FK_4178682C8F5EA509 FOREIGN KEY (classe_id) REFERENCES classe (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE `classe_weapon` ADD CONSTRAINT FK_4178682C126F525E FOREIGN KEY (item_id) REFERENCES item (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE `classe_tool` ADD CONSTRAINT FK_3EE04B378F5EA509 FOREIGN KEY (classe_id) REFERENCES classe (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE `classe_tool` ADD CONSTRAINT FK_3EE04B37126F525E FOREIGN KEY (item_id) REFERENCES item (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE classe_competence ADD CONSTRAINT FK_31EF89548F5EA509 FOREIGN KEY (classe_id) REFERENCES classe (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE classe_competence ADD CONSTRAINT FK_31EF895415761DAB FOREIGN KEY (competence_id) REFERENCES competence (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE `classe_armors` ADD CONSTRAINT FK_87F199088F5EA509 FOREIGN KEY (classe_id) REFERENCES classe (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE `classe_armors` ADD CONSTRAINT FK_87F199084C2B59A3 FOREIGN KEY (item_subcategory_id) REFERENCES item_subcategory (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE `classe_weapons` ADD CONSTRAINT FK_2997DB808F5EA509 FOREIGN KEY (classe_id) REFERENCES classe (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE `classe_weapons` ADD CONSTRAINT FK_2997DB804C2B59A3 FOREIGN KEY (item_subcategory_id) REFERENCES item_subcategory (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE classe_level ADD CONSTRAINT FK_D39D982B8F5EA509 FOREIGN KEY (classe_id) REFERENCES classe (id)');
        $this->addSql('ALTER TABLE feat ADD CONSTRAINT FK_5A9B91CB953C1C61 FOREIGN KEY (source_id) REFERENCES source (id)');
        $this->addSql('ALTER TABLE feat ADD CONSTRAINT FK_5A9B91CB53CF384 FOREIGN KEY (source_part_id) REFERENCES source_part (id)');
        $this->addSql('ALTER TABLE item ADD CONSTRAINT FK_1F1B251E5DC6FE57 FOREIGN KEY (subcategory_id) REFERENCES item_subcategory (id)');
        $this->addSql('ALTER TABLE item ADD CONSTRAINT FK_1F1B251E12469DE2 FOREIGN KEY (category_id) REFERENCES item_category (id)');
        $this->addSql('ALTER TABLE item ADD CONSTRAINT FK_1F1B251E91B04077 FOREIGN KEY (damage2_id) REFERENCES damage (id)');
        $this->addSql('ALTER TABLE item ADD CONSTRAINT FK_1F1B251E953C1C61 FOREIGN KEY (source_id) REFERENCES source (id)');
        $this->addSql('ALTER TABLE item ADD CONSTRAINT FK_1F1B251E53CF384 FOREIGN KEY (source_part_id) REFERENCES source_part (id)');
        $this->addSql('ALTER TABLE item_category_source ADD CONSTRAINT FK_EAA36EAAF22EC5D4 FOREIGN KEY (item_category_id) REFERENCES item_category (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE item_category_source ADD CONSTRAINT FK_EAA36EAA953C1C61 FOREIGN KEY (source_id) REFERENCES source (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE item_category_source_part ADD CONSTRAINT FK_8AEBFF85F22EC5D4 FOREIGN KEY (item_category_id) REFERENCES item_category (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE item_category_source_part ADD CONSTRAINT FK_8AEBFF8553CF384 FOREIGN KEY (source_part_id) REFERENCES source_part (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE item_property_item ADD CONSTRAINT FK_ECAF32FFB4FA4BDA FOREIGN KEY (item_property_id) REFERENCES item_property (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE item_property_item ADD CONSTRAINT FK_ECAF32FF126F525E FOREIGN KEY (item_id) REFERENCES item (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE item_subcategory ADD CONSTRAINT FK_EDB4FC7E12469DE2 FOREIGN KEY (category_id) REFERENCES item_category (id)');
        $this->addSql('ALTER TABLE liste ADD CONSTRAINT FK_FCF22AF45585C142 FOREIGN KEY (skill_id) REFERENCES skill (id)');
        $this->addSql('ALTER TABLE liste ADD CONSTRAINT FK_FCF22AF4479EC90D FOREIGN KEY (spell_id) REFERENCES spell (id)');
        $this->addSql('ALTER TABLE liste_item_subcategory ADD CONSTRAINT FK_A97D3CC3E85441D8 FOREIGN KEY (liste_id) REFERENCES liste (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE liste_item_subcategory ADD CONSTRAINT FK_A97D3CC34C2B59A3 FOREIGN KEY (item_subcategory_id) REFERENCES item_subcategory (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE race_source ADD CONSTRAINT FK_35DC61A06E59D40D FOREIGN KEY (race_id) REFERENCES race (id)');
        $this->addSql('ALTER TABLE race_source ADD CONSTRAINT FK_35DC61A0953C1C61 FOREIGN KEY (source_id) REFERENCES source (id)');
        $this->addSql('ALTER TABLE race_source ADD CONSTRAINT FK_35DC61A053CF384 FOREIGN KEY (source_part_id) REFERENCES source_part (id)');
        $this->addSql('ALTER TABLE race_source_language ADD CONSTRAINT FK_3A2AE9334CBA5C7C FOREIGN KEY (race_source_id) REFERENCES race_source (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE race_source_language ADD CONSTRAINT FK_3A2AE93382F1BAF4 FOREIGN KEY (language_id) REFERENCES language (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE race_subrace ADD CONSTRAINT FK_1C6A1C54953C1C61 FOREIGN KEY (source_id) REFERENCES race_source (id)');
        $this->addSql('ALTER TABLE sb ADD CONSTRAINT FK_E67738BEC54C8C93 FOREIGN KEY (type_id) REFERENCES creature_type (id)');
        $this->addSql('ALTER TABLE sb ADD CONSTRAINT FK_E67738BE953C1C61 FOREIGN KEY (source_id) REFERENCES source (id)');
        $this->addSql('ALTER TABLE sb ADD CONSTRAINT FK_E67738BE53CF384 FOREIGN KEY (source_part_id) REFERENCES source_part (id)');
        $this->addSql('ALTER TABLE sb ADD CONSTRAINT FK_E67738BEAB7AC2A0 FOREIGN KEY (alignment_id) REFERENCES alignment (id)');
        $this->addSql('ALTER TABLE sb_sense ADD CONSTRAINT FK_6F056A12707F4EA8 FOREIGN KEY (sb_id) REFERENCES sb (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE sb_sense ADD CONSTRAINT FK_6F056A128707C57E FOREIGN KEY (sense_id) REFERENCES sense (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE sb_speed ADD CONSTRAINT FK_6F08A71F707F4EA8 FOREIGN KEY (sb_id) REFERENCES sb (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE sb_speed ADD CONSTRAINT FK_6F08A71F8F3A8393 FOREIGN KEY (speed_id) REFERENCES speed (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE sbskill ADD CONSTRAINT FK_9DCFA8F36CE425B7 FOREIGN KEY (damage_id) REFERENCES damage (id)');
        $this->addSql('ALTER TABLE sbskill_sb ADD CONSTRAINT FK_E588BE0ABCC6E1E4 FOREIGN KEY (sbskill_id) REFERENCES sbskill (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE sbskill_sb ADD CONSTRAINT FK_E588BE0A707F4EA8 FOREIGN KEY (sb_id) REFERENCES sb (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE sbspecialty ADD CONSTRAINT FK_DF3AE311C5FF1223 FOREIGN KEY (monster_id) REFERENCES sb (id)');
        $this->addSql('ALTER TABLE sbspecialty ADD CONSTRAINT FK_DF3AE3115585C142 FOREIGN KEY (skill_id) REFERENCES sbskill (id)');
        $this->addSql('ALTER TABLE skill ADD CONSTRAINT FK_5E3DE477F43C4D5C FOREIGN KEY (feat_id) REFERENCES feat (id)');
        $this->addSql('ALTER TABLE skill ADD CONSTRAINT FK_5E3DE47733EF40B5 FOREIGN KEY (spellcasting_id) REFERENCES classe_spellcasting (id)');
        $this->addSql('ALTER TABLE skill ADD CONSTRAINT FK_5E3DE477C5FF1223 FOREIGN KEY (monster_id) REFERENCES sb (id)');
        $this->addSql('ALTER TABLE skill_bg ADD CONSTRAINT FK_2F7849335585C142 FOREIGN KEY (skill_id) REFERENCES skill (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE skill_bg ADD CONSTRAINT FK_2F7849331A2100A8 FOREIGN KEY (bg_id) REFERENCES bg (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE skill_item_category ADD CONSTRAINT FK_84DDDCB65585C142 FOREIGN KEY (skill_id) REFERENCES skill (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE skill_item_category ADD CONSTRAINT FK_84DDDCB6F22EC5D4 FOREIGN KEY (item_category_id) REFERENCES item_category (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE skill_item_subcategory ADD CONSTRAINT FK_6DE75AC65585C142 FOREIGN KEY (skill_id) REFERENCES skill (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE skill_item_subcategory ADD CONSTRAINT FK_6DE75AC64C2B59A3 FOREIGN KEY (item_subcategory_id) REFERENCES item_subcategory (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE skill_classe_level ADD CONSTRAINT FK_41F108295585C142 FOREIGN KEY (skill_id) REFERENCES skill (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE skill_classe_level ADD CONSTRAINT FK_41F10829657F8309 FOREIGN KEY (classe_level_id) REFERENCES classe_level (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE skill_specialty_item ADD CONSTRAINT FK_17071ED65585C142 FOREIGN KEY (skill_id) REFERENCES skill (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE skill_specialty_item ADD CONSTRAINT FK_17071ED6605A4EC1 FOREIGN KEY (specialty_item_id) REFERENCES specialty_item (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE skill_race_source ADD CONSTRAINT FK_8BC2F86C5585C142 FOREIGN KEY (skill_id) REFERENCES skill (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE skill_race_source ADD CONSTRAINT FK_8BC2F86C4CBA5C7C FOREIGN KEY (race_source_id) REFERENCES race_source (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE skill_race_subrace ADD CONSTRAINT FK_8E068C565585C142 FOREIGN KEY (skill_id) REFERENCES skill (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE skill_race_subrace ADD CONSTRAINT FK_8E068C5646E4965B FOREIGN KEY (race_subrace_id) REFERENCES race_subrace (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE source_part ADD CONSTRAINT FK_4885F5C5953C1C61 FOREIGN KEY (source_id) REFERENCES source (id)');
        $this->addSql('ALTER TABLE specialty ADD CONSTRAINT FK_E066A6EC8F5EA509 FOREIGN KEY (classe_id) REFERENCES classe (id)');
        $this->addSql('ALTER TABLE specialty_item_specialty ADD CONSTRAINT FK_29DF2BC8605A4EC1 FOREIGN KEY (specialty_item_id) REFERENCES specialty_item (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE specialty_item_specialty ADD CONSTRAINT FK_29DF2BC89A353316 FOREIGN KEY (specialty_id) REFERENCES specialty (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE specialty_item_source ADD CONSTRAINT FK_355673FC605A4EC1 FOREIGN KEY (specialty_item_id) REFERENCES specialty_item (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE specialty_item_source ADD CONSTRAINT FK_355673FC953C1C61 FOREIGN KEY (source_id) REFERENCES source (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE specialty_item_source_part ADD CONSTRAINT FK_2A642247605A4EC1 FOREIGN KEY (specialty_item_id) REFERENCES specialty_item (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE specialty_item_source_part ADD CONSTRAINT FK_2A64224753CF384 FOREIGN KEY (source_part_id) REFERENCES source_part (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE spell ADD CONSTRAINT FK_D03FCD8DC32A47EE FOREIGN KEY (school_id) REFERENCES school (id)');
        $this->addSql('ALTER TABLE spell ADD CONSTRAINT FK_D03FCD8D953C1C61 FOREIGN KEY (source_id) REFERENCES source (id)');
        $this->addSql('ALTER TABLE spell ADD CONSTRAINT FK_D03FCD8D53CF384 FOREIGN KEY (source_part_id) REFERENCES source_part (id)');
        $this->addSql('ALTER TABLE spell_classe ADD CONSTRAINT FK_37264883479EC90D FOREIGN KEY (spell_id) REFERENCES spell (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE spell_classe ADD CONSTRAINT FK_372648838F5EA509 FOREIGN KEY (classe_id) REFERENCES classe (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE `classe_spell_expanded` ADD CONSTRAINT FK_1ADD7654479EC90D FOREIGN KEY (spell_id) REFERENCES spell (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE `classe_spell_expanded` ADD CONSTRAINT FK_1ADD76548F5EA509 FOREIGN KEY (classe_id) REFERENCES classe (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE subskill ADD CONSTRAINT FK_248E0BAD5585C142 FOREIGN KEY (skill_id) REFERENCES skill (id)');
        $this->addSql('ALTER TABLE `table` ADD CONSTRAINT FK_F6298F465585C142 FOREIGN KEY (skill_id) REFERENCES skill (id)');
        $this->addSql('ALTER TABLE `table` ADD CONSTRAINT FK_F6298F46DC61594A FOREIGN KEY (bg_carac_id) REFERENCES bgcarac (id)');
        $this->addSql('ALTER TABLE `table` ADD CONSTRAINT FK_F6298F46479EC90D FOREIGN KEY (spell_id) REFERENCES spell (id)');
        $this->addSql('ALTER TABLE table_item ADD CONSTRAINT FK_55CD65D5ECFF285C FOREIGN KEY (table_id) REFERENCES `table` (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE table_item ADD CONSTRAINT FK_55CD65D5126F525E FOREIGN KEY (item_id) REFERENCES item (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE table_item_subcategory ADD CONSTRAINT FK_379EF18ECFF285C FOREIGN KEY (table_id) REFERENCES `table` (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE table_item_subcategory ADD CONSTRAINT FK_379EF184C2B59A3 FOREIGN KEY (item_subcategory_id) REFERENCES item_subcategory (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE table_specialty_item ADD CONSTRAINT FK_ABFADE81ECFF285C FOREIGN KEY (table_id) REFERENCES `table` (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE table_specialty_item ADD CONSTRAINT FK_ABFADE81605A4EC1 FOREIGN KEY (specialty_item_id) REFERENCES specialty_item (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE table_race_source ADD CONSTRAINT FK_682921DECFF285C FOREIGN KEY (table_id) REFERENCES `table` (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE table_race_source ADD CONSTRAINT FK_682921D4CBA5C7C FOREIGN KEY (race_source_id) REFERENCES race_source (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE table_race_subrace ADD CONSTRAINT FK_A9898D96ECFF285C FOREIGN KEY (table_id) REFERENCES `table` (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE table_race_subrace ADD CONSTRAINT FK_A9898D9646E4965B FOREIGN KEY (race_subrace_id) REFERENCES race_subrace (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE table_row ADD CONSTRAINT FK_8DD57CBFB062D5BC FOREIGN KEY (tableau_id) REFERENCES `table` (id)');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE bg DROP FOREIGN KEY FK_C5C4EF21953C1C61');
        $this->addSql('ALTER TABLE bg DROP FOREIGN KEY FK_C5C4EF2153CF384');
        $this->addSql('ALTER TABLE bg_competence DROP FOREIGN KEY FK_A10985FB1A2100A8');
        $this->addSql('ALTER TABLE bg_competence DROP FOREIGN KEY FK_A10985FB15761DAB');
        $this->addSql('ALTER TABLE bg_language DROP FOREIGN KEY FK_4C16A1671A2100A8');
        $this->addSql('ALTER TABLE bg_language DROP FOREIGN KEY FK_4C16A16782F1BAF4');
        $this->addSql('ALTER TABLE bgcarac DROP FOREIGN KEY FK_3694F6911A2100A8');
        $this->addSql('ALTER TABLE classe DROP FOREIGN KEY FK_8F87BF96568477C4');
        $this->addSql('ALTER TABLE classe DROP FOREIGN KEY FK_8F87BF9633EF40B5');
        $this->addSql('ALTER TABLE `classe_armor` DROP FOREIGN KEY FK_F650AAC48F5EA509');
        $this->addSql('ALTER TABLE `classe_armor` DROP FOREIGN KEY FK_F650AAC4126F525E');
        $this->addSql('ALTER TABLE `classe_weapon` DROP FOREIGN KEY FK_4178682C8F5EA509');
        $this->addSql('ALTER TABLE `classe_weapon` DROP FOREIGN KEY FK_4178682C126F525E');
        $this->addSql('ALTER TABLE `classe_tool` DROP FOREIGN KEY FK_3EE04B378F5EA509');
        $this->addSql('ALTER TABLE `classe_tool` DROP FOREIGN KEY FK_3EE04B37126F525E');
        $this->addSql('ALTER TABLE classe_competence DROP FOREIGN KEY FK_31EF89548F5EA509');
        $this->addSql('ALTER TABLE classe_competence DROP FOREIGN KEY FK_31EF895415761DAB');
        $this->addSql('ALTER TABLE `classe_armors` DROP FOREIGN KEY FK_87F199088F5EA509');
        $this->addSql('ALTER TABLE `classe_armors` DROP FOREIGN KEY FK_87F199084C2B59A3');
        $this->addSql('ALTER TABLE `classe_weapons` DROP FOREIGN KEY FK_2997DB808F5EA509');
        $this->addSql('ALTER TABLE `classe_weapons` DROP FOREIGN KEY FK_2997DB804C2B59A3');
        $this->addSql('ALTER TABLE classe_level DROP FOREIGN KEY FK_D39D982B8F5EA509');
        $this->addSql('ALTER TABLE feat DROP FOREIGN KEY FK_5A9B91CB953C1C61');
        $this->addSql('ALTER TABLE feat DROP FOREIGN KEY FK_5A9B91CB53CF384');
        $this->addSql('ALTER TABLE item DROP FOREIGN KEY FK_1F1B251E5DC6FE57');
        $this->addSql('ALTER TABLE item DROP FOREIGN KEY FK_1F1B251E12469DE2');
        $this->addSql('ALTER TABLE item DROP FOREIGN KEY FK_1F1B251E91B04077');
        $this->addSql('ALTER TABLE item DROP FOREIGN KEY FK_1F1B251E953C1C61');
        $this->addSql('ALTER TABLE item DROP FOREIGN KEY FK_1F1B251E53CF384');
        $this->addSql('ALTER TABLE item_category_source DROP FOREIGN KEY FK_EAA36EAAF22EC5D4');
        $this->addSql('ALTER TABLE item_category_source DROP FOREIGN KEY FK_EAA36EAA953C1C61');
        $this->addSql('ALTER TABLE item_category_source_part DROP FOREIGN KEY FK_8AEBFF85F22EC5D4');
        $this->addSql('ALTER TABLE item_category_source_part DROP FOREIGN KEY FK_8AEBFF8553CF384');
        $this->addSql('ALTER TABLE item_property_item DROP FOREIGN KEY FK_ECAF32FFB4FA4BDA');
        $this->addSql('ALTER TABLE item_property_item DROP FOREIGN KEY FK_ECAF32FF126F525E');
        $this->addSql('ALTER TABLE item_subcategory DROP FOREIGN KEY FK_EDB4FC7E12469DE2');
        $this->addSql('ALTER TABLE liste DROP FOREIGN KEY FK_FCF22AF45585C142');
        $this->addSql('ALTER TABLE liste DROP FOREIGN KEY FK_FCF22AF4479EC90D');
        $this->addSql('ALTER TABLE liste_item_subcategory DROP FOREIGN KEY FK_A97D3CC3E85441D8');
        $this->addSql('ALTER TABLE liste_item_subcategory DROP FOREIGN KEY FK_A97D3CC34C2B59A3');
        $this->addSql('ALTER TABLE race_source DROP FOREIGN KEY FK_35DC61A06E59D40D');
        $this->addSql('ALTER TABLE race_source DROP FOREIGN KEY FK_35DC61A0953C1C61');
        $this->addSql('ALTER TABLE race_source DROP FOREIGN KEY FK_35DC61A053CF384');
        $this->addSql('ALTER TABLE race_source_language DROP FOREIGN KEY FK_3A2AE9334CBA5C7C');
        $this->addSql('ALTER TABLE race_source_language DROP FOREIGN KEY FK_3A2AE93382F1BAF4');
        $this->addSql('ALTER TABLE race_subrace DROP FOREIGN KEY FK_1C6A1C54953C1C61');
        $this->addSql('ALTER TABLE sb DROP FOREIGN KEY FK_E67738BEC54C8C93');
        $this->addSql('ALTER TABLE sb DROP FOREIGN KEY FK_E67738BE953C1C61');
        $this->addSql('ALTER TABLE sb DROP FOREIGN KEY FK_E67738BE53CF384');
        $this->addSql('ALTER TABLE sb DROP FOREIGN KEY FK_E67738BEAB7AC2A0');
        $this->addSql('ALTER TABLE sb_sense DROP FOREIGN KEY FK_6F056A12707F4EA8');
        $this->addSql('ALTER TABLE sb_sense DROP FOREIGN KEY FK_6F056A128707C57E');
        $this->addSql('ALTER TABLE sb_speed DROP FOREIGN KEY FK_6F08A71F707F4EA8');
        $this->addSql('ALTER TABLE sb_speed DROP FOREIGN KEY FK_6F08A71F8F3A8393');
        $this->addSql('ALTER TABLE sbskill DROP FOREIGN KEY FK_9DCFA8F36CE425B7');
        $this->addSql('ALTER TABLE sbskill_sb DROP FOREIGN KEY FK_E588BE0ABCC6E1E4');
        $this->addSql('ALTER TABLE sbskill_sb DROP FOREIGN KEY FK_E588BE0A707F4EA8');
        $this->addSql('ALTER TABLE sbspecialty DROP FOREIGN KEY FK_DF3AE311C5FF1223');
        $this->addSql('ALTER TABLE sbspecialty DROP FOREIGN KEY FK_DF3AE3115585C142');
        $this->addSql('ALTER TABLE skill DROP FOREIGN KEY FK_5E3DE477F43C4D5C');
        $this->addSql('ALTER TABLE skill DROP FOREIGN KEY FK_5E3DE47733EF40B5');
        $this->addSql('ALTER TABLE skill DROP FOREIGN KEY FK_5E3DE477C5FF1223');
        $this->addSql('ALTER TABLE skill_bg DROP FOREIGN KEY FK_2F7849335585C142');
        $this->addSql('ALTER TABLE skill_bg DROP FOREIGN KEY FK_2F7849331A2100A8');
        $this->addSql('ALTER TABLE skill_item_category DROP FOREIGN KEY FK_84DDDCB65585C142');
        $this->addSql('ALTER TABLE skill_item_category DROP FOREIGN KEY FK_84DDDCB6F22EC5D4');
        $this->addSql('ALTER TABLE skill_item_subcategory DROP FOREIGN KEY FK_6DE75AC65585C142');
        $this->addSql('ALTER TABLE skill_item_subcategory DROP FOREIGN KEY FK_6DE75AC64C2B59A3');
        $this->addSql('ALTER TABLE skill_classe_level DROP FOREIGN KEY FK_41F108295585C142');
        $this->addSql('ALTER TABLE skill_classe_level DROP FOREIGN KEY FK_41F10829657F8309');
        $this->addSql('ALTER TABLE skill_specialty_item DROP FOREIGN KEY FK_17071ED65585C142');
        $this->addSql('ALTER TABLE skill_specialty_item DROP FOREIGN KEY FK_17071ED6605A4EC1');
        $this->addSql('ALTER TABLE skill_race_source DROP FOREIGN KEY FK_8BC2F86C5585C142');
        $this->addSql('ALTER TABLE skill_race_source DROP FOREIGN KEY FK_8BC2F86C4CBA5C7C');
        $this->addSql('ALTER TABLE skill_race_subrace DROP FOREIGN KEY FK_8E068C565585C142');
        $this->addSql('ALTER TABLE skill_race_subrace DROP FOREIGN KEY FK_8E068C5646E4965B');
        $this->addSql('ALTER TABLE source_part DROP FOREIGN KEY FK_4885F5C5953C1C61');
        $this->addSql('ALTER TABLE specialty DROP FOREIGN KEY FK_E066A6EC8F5EA509');
        $this->addSql('ALTER TABLE specialty_item_specialty DROP FOREIGN KEY FK_29DF2BC8605A4EC1');
        $this->addSql('ALTER TABLE specialty_item_specialty DROP FOREIGN KEY FK_29DF2BC89A353316');
        $this->addSql('ALTER TABLE specialty_item_source DROP FOREIGN KEY FK_355673FC605A4EC1');
        $this->addSql('ALTER TABLE specialty_item_source DROP FOREIGN KEY FK_355673FC953C1C61');
        $this->addSql('ALTER TABLE specialty_item_source_part DROP FOREIGN KEY FK_2A642247605A4EC1');
        $this->addSql('ALTER TABLE specialty_item_source_part DROP FOREIGN KEY FK_2A64224753CF384');
        $this->addSql('ALTER TABLE spell DROP FOREIGN KEY FK_D03FCD8DC32A47EE');
        $this->addSql('ALTER TABLE spell DROP FOREIGN KEY FK_D03FCD8D953C1C61');
        $this->addSql('ALTER TABLE spell DROP FOREIGN KEY FK_D03FCD8D53CF384');
        $this->addSql('ALTER TABLE spell_classe DROP FOREIGN KEY FK_37264883479EC90D');
        $this->addSql('ALTER TABLE spell_classe DROP FOREIGN KEY FK_372648838F5EA509');
        $this->addSql('ALTER TABLE `classe_spell_expanded` DROP FOREIGN KEY FK_1ADD7654479EC90D');
        $this->addSql('ALTER TABLE `classe_spell_expanded` DROP FOREIGN KEY FK_1ADD76548F5EA509');
        $this->addSql('ALTER TABLE subskill DROP FOREIGN KEY FK_248E0BAD5585C142');
        $this->addSql('ALTER TABLE `table` DROP FOREIGN KEY FK_F6298F465585C142');
        $this->addSql('ALTER TABLE `table` DROP FOREIGN KEY FK_F6298F46DC61594A');
        $this->addSql('ALTER TABLE `table` DROP FOREIGN KEY FK_F6298F46479EC90D');
        $this->addSql('ALTER TABLE table_item DROP FOREIGN KEY FK_55CD65D5ECFF285C');
        $this->addSql('ALTER TABLE table_item DROP FOREIGN KEY FK_55CD65D5126F525E');
        $this->addSql('ALTER TABLE table_item_subcategory DROP FOREIGN KEY FK_379EF18ECFF285C');
        $this->addSql('ALTER TABLE table_item_subcategory DROP FOREIGN KEY FK_379EF184C2B59A3');
        $this->addSql('ALTER TABLE table_specialty_item DROP FOREIGN KEY FK_ABFADE81ECFF285C');
        $this->addSql('ALTER TABLE table_specialty_item DROP FOREIGN KEY FK_ABFADE81605A4EC1');
        $this->addSql('ALTER TABLE table_race_source DROP FOREIGN KEY FK_682921DECFF285C');
        $this->addSql('ALTER TABLE table_race_source DROP FOREIGN KEY FK_682921D4CBA5C7C');
        $this->addSql('ALTER TABLE table_race_subrace DROP FOREIGN KEY FK_A9898D96ECFF285C');
        $this->addSql('ALTER TABLE table_race_subrace DROP FOREIGN KEY FK_A9898D9646E4965B');
        $this->addSql('ALTER TABLE table_row DROP FOREIGN KEY FK_8DD57CBFB062D5BC');
        $this->addSql('DROP TABLE alignment');
        $this->addSql('DROP TABLE bg');
        $this->addSql('DROP TABLE bg_competence');
        $this->addSql('DROP TABLE bg_language');
        $this->addSql('DROP TABLE bgcarac');
        $this->addSql('DROP TABLE classe');
        $this->addSql('DROP TABLE `classe_armor`');
        $this->addSql('DROP TABLE `classe_weapon`');
        $this->addSql('DROP TABLE `classe_tool`');
        $this->addSql('DROP TABLE classe_competence');
        $this->addSql('DROP TABLE `classe_armors`');
        $this->addSql('DROP TABLE `classe_weapons`');
        $this->addSql('DROP TABLE classe_level');
        $this->addSql('DROP TABLE classe_spellcasting');
        $this->addSql('DROP TABLE competence');
        $this->addSql('DROP TABLE `condition`');
        $this->addSql('DROP TABLE creature_type');
        $this->addSql('DROP TABLE damage');
        $this->addSql('DROP TABLE feat');
        $this->addSql('DROP TABLE item');
        $this->addSql('DROP TABLE item_category');
        $this->addSql('DROP TABLE item_category_source');
        $this->addSql('DROP TABLE item_category_source_part');
        $this->addSql('DROP TABLE item_property');
        $this->addSql('DROP TABLE item_property_item');
        $this->addSql('DROP TABLE item_subcategory');
        $this->addSql('DROP TABLE language');
        $this->addSql('DROP TABLE liste');
        $this->addSql('DROP TABLE liste_item_subcategory');
        $this->addSql('DROP TABLE race');
        $this->addSql('DROP TABLE race_source');
        $this->addSql('DROP TABLE race_source_language');
        $this->addSql('DROP TABLE race_subrace');
        $this->addSql('DROP TABLE sb');
        $this->addSql('DROP TABLE sb_sense');
        $this->addSql('DROP TABLE sb_speed');
        $this->addSql('DROP TABLE sbskill');
        $this->addSql('DROP TABLE sbskill_sb');
        $this->addSql('DROP TABLE sbspecialty');
        $this->addSql('DROP TABLE school');
        $this->addSql('DROP TABLE sense');
        $this->addSql('DROP TABLE skill');
        $this->addSql('DROP TABLE skill_bg');
        $this->addSql('DROP TABLE skill_item_category');
        $this->addSql('DROP TABLE skill_item_subcategory');
        $this->addSql('DROP TABLE skill_classe_level');
        $this->addSql('DROP TABLE skill_specialty_item');
        $this->addSql('DROP TABLE skill_race_source');
        $this->addSql('DROP TABLE skill_race_subrace');
        $this->addSql('DROP TABLE source');
        $this->addSql('DROP TABLE source_part');
        $this->addSql('DROP TABLE specialty');
        $this->addSql('DROP TABLE specialty_item');
        $this->addSql('DROP TABLE specialty_item_specialty');
        $this->addSql('DROP TABLE specialty_item_source');
        $this->addSql('DROP TABLE specialty_item_source_part');
        $this->addSql('DROP TABLE speed');
        $this->addSql('DROP TABLE spell');
        $this->addSql('DROP TABLE spell_classe');
        $this->addSql('DROP TABLE `classe_spell_expanded`');
        $this->addSql('DROP TABLE subskill');
        $this->addSql('DROP TABLE `table`');
        $this->addSql('DROP TABLE table_item');
        $this->addSql('DROP TABLE table_item_subcategory');
        $this->addSql('DROP TABLE table_specialty_item');
        $this->addSql('DROP TABLE table_race_source');
        $this->addSql('DROP TABLE table_race_subrace');
        $this->addSql('DROP TABLE table_row');
        $this->addSql('DROP TABLE user');
        $this->addSql('DROP TABLE messenger_messages');
    }
}
